import Head from 'next/head';

import TodoItem from '@/components/TodoItem';

import helloImg from '../images/waving-hand.png';

import axios from '../API/axios';
import React from 'react';
import { useAppDispatch, useAppSelector } from '../redux/hooks/index';
import { getItems } from '@/redux/slices/ItemSlice';
import { Grid } from '@mui/material';
import { selectAuth, login } from './../redux/slices/AuthSlice';
import Link from 'next/link';
import Image from 'next/image';
import Router from 'next/router';

import styles from '../styles/start.module.scss';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';

import { wrapper } from '@/redux/store';
import { GetServerSideProps } from 'next';

import { parseCookies } from 'nookies';
import { getMe } from './../redux/slices/AuthSlice';
export default function Home() {
  const dispatch = useAppDispatch();

  const isAuth = useAppSelector(selectAuth);

  // React.useEffect(() => {
  //   dispatch(getMe());
  // }, []);

  React.useEffect(() => {
    if (isAuth) {
      Router.push('/allTodos');
    }
  }, [isAuth]);

  console.log('index isAuth', isAuth);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <div className={styles.header}>
          <Stack direction="row" justifyContent="center" alignItems=" center" gap="2rem">
            <Image src={helloImg} alt="" width={100}></Image>
            <span>Welcome!</span>
          </Stack>

          <Stack direction="row" gap="2rem" alignItems="center">
            <Link href="/login">
              <Button variant="contained">Login</Button>
            </Link>
            <Typography>Or</Typography>
            <Link href="/register">
              <Button variant="contained">Register</Button>
            </Link>
          </Stack>
        </div>
        <div></div>
      </>
    </>
  );
}

// export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps(
//   (store) => async (ctx) => {
//     try {
//       const { token } = parseCookies(ctx);
//       const userData = await store.dispatch(getMe(token));
//       store.dispatch(login(userData));
//       console.log(userData);
//       return { props: {} };
//     } catch (error) {
//       console.log(error);
//       return { props: {} };
//     }
//   },
// );
